services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./.docker-volumes/mongo/data:/data/db
      - ./mongo-entrypoint/:/docker-entrypoint-initdb.d/
    env_file:
      - .env
    networks:
      - lego-network
  nest:
    image: registry.cn-beijing.aliyuncs.com/kaixinliu/lego-backend:{{IMAGE_TAG}}
    depends_on:
      - mongo
    ports:
      - 9005:3302
    networks:
      - lego-network
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 81:80
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/
    networks:
      - lego-network
networks:
  lego-network:
